<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
class RolesXProfesorTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        DB::table('roles_x_profesor')->delete();
        
        DB::table('roles_x_profesor')->insert(array (
            0 => 
            array (
                'id' => 1,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:55',
                'updated_at' => NULL,
                'id_rol' => 1,
                'fecha_fin' => NULL,
                'legajo_prof' => 8394918,
                'sit_revista' => 'TITULAR',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:55',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 8394918,
                'sit_revista' => 'TITULAR',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:55',
                'updated_at' => NULL,
                'id_rol' => 2,
                'fecha_fin' => NULL,
                'legajo_prof' => 14955900,
                'sit_revista' => 'TITULAR',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:55',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 14955900,
                'sit_revista' => 'TITULAR',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:55',
                'updated_at' => NULL,
                'id_rol' => 3,
                'fecha_fin' => NULL,
                'legajo_prof' => 145938,
                'sit_revista' => 'TITULAR',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:55',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 145938,
                'sit_revista' => 'TITULAR',
                'observacion' => 'Cambio funciones transitorio',
                'descripcion' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:55',
                'updated_at' => NULL,
                'id_rol' => 8,
                'fecha_fin' => NULL,
                'legajo_prof' => 145938,
                'sit_revista' => 'TITULAR',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:55',
                'updated_at' => NULL,
                'id_rol' => 9,
                'fecha_fin' => NULL,
                'legajo_prof' => 14542518,
                'sit_revista' => 'TITULAR',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:55',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 14542518,
                'sit_revista' => 'TITULAR',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:55',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 14542518,
                'sit_revista' => 'PROVISIONAL',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:55',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 17354500,
                'sit_revista' => 'TITULAR',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:55',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 17354500,
                'sit_revista' => 'PROVISIONAL',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:55',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 23143400,
                'sit_revista' => 'PROVISIONAL',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:55',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 19377800,
                'sit_revista' => 'TITULAR',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:55',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 19377800,
                'sit_revista' => 'PROVISIONAL',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:55',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 25838900,
                'sit_revista' => 'PROVISIONAL',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:55',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 23972300,
                'sit_revista' => 'PROVISIONAL',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:55',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 18661200,
                'sit_revista' => 'TITULAR',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:55',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 17868918,
                'sit_revista' => 'TITULAR',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:55',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 19887800,
                'sit_revista' => 'TITULAR',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:55',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 19887800,
                'sit_revista' => 'PROVISIONAL',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:55',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 182534,
                'sit_revista' => 'TITULAR',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:55',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 186401,
                'sit_revista' => 'TITULAR',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:55',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 18165600,
                'sit_revista' => 'TITULAR',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 18165600,
                'sit_revista' => 'PROVISIONAL',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 5,
                'fecha_fin' => NULL,
                'legajo_prof' => 10807600,
                'sit_revista' => 'TITULAR',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 5,
                'fecha_fin' => NULL,
                'legajo_prof' => 10807600,
                'sit_revista' => 'SUPLENTE',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 20808900,
                'sit_revista' => 'TITULAR',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 20212300,
                'sit_revista' => 'TITULAR',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 247623,
                'sit_revista' => 'TITULAR',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 247623,
                'sit_revista' => 'PROVISIONAL',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 5,
                'fecha_fin' => NULL,
                'legajo_prof' => 17066700,
                'sit_revista' => 'TITULAR',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 186412,
                'sit_revista' => 'TITULAR',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 186412,
                'sit_revista' => 'PROVISIONAL',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 8338619,
                'sit_revista' => 'TITULAR',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 20868900,
                'sit_revista' => 'TITULAR',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 187934,
                'sit_revista' => 'TITULAR',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 187934,
                'sit_revista' => 'PROVISIONAL',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 68833,
                'sit_revista' => 'TITULAR',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 22060100,
                'sit_revista' => 'TITULAR',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 22060100,
                'sit_revista' => 'PROVISIONAL',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 5,
                'fecha_fin' => NULL,
                'legajo_prof' => 113178700,
                'sit_revista' => 'TITULAR',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 5,
                'fecha_fin' => NULL,
                'legajo_prof' => 17740100,
                'sit_revista' => 'TITULAR',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 178267,
                'sit_revista' => 'TITULAR',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 18897818,
                'sit_revista' => 'PROVISIONAL',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 18897818,
                'sit_revista' => 'SUPLENTE',
                'observacion' => 'por susser baja el 24/128/2022',
                'descripcion' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 26682300,
                'sit_revista' => 'PROVISIONAL',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 26682300,
                'sit_revista' => 'SUPLENTE',
                'observacion' => 'POR MELICCHIO',
                'descripcion' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 20769000,
                'sit_revista' => 'TITULAR',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 20769000,
                'sit_revista' => 'PROVISIONAL',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 203567,
                'sit_revista' => 'TITULAR',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 203567,
                'sit_revista' => 'PROVISIONAL',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 3542800,
                'sit_revista' => 'TITULAR',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 24195619,
                'sit_revista' => 'TITULAR',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 24195619,
                'sit_revista' => 'PROV/TIT',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 24195619,
                'sit_revista' => 'SUPLENTE',
                'observacion' => 'POR D´AQUINO BAJA EL 20/12/2022',
                'descripcion' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 8397200,
                'sit_revista' => 'TITULAR',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            57 => 
            array (
                'id' => 58,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 8397200,
                'sit_revista' => 'PROVISIONAL',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            58 => 
            array (
                'id' => 59,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 8397200,
                'sit_revista' => 'SUPLENTE',
                'observacion' => 'POR VARRICA',
                'descripcion' => NULL,
            ),
            59 => 
            array (
                'id' => 60,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 5,
                'fecha_fin' => NULL,
                'legajo_prof' => 145037,
                'sit_revista' => 'TITULAR',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            60 => 
            array (
                'id' => 61,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 20770118,
                'sit_revista' => 'SUPLENTE',
                'observacion' => 'POR VARRICA',
                'descripcion' => NULL,
            ),
            61 => 
            array (
                'id' => 62,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 20770118,
                'sit_revista' => 'PROVISIONAL',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            62 => 
            array (
                'id' => 63,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 5,
                'fecha_fin' => NULL,
                'legajo_prof' => 145920,
                'sit_revista' => 'TITULAR',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            63 => 
            array (
                'id' => 64,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 5,
                'fecha_fin' => NULL,
                'legajo_prof' => 174345,
                'sit_revista' => 'TITULAR',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            64 => 
            array (
                'id' => 65,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 235434,
                'sit_revista' => 'TITULAR',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            65 => 
            array (
                'id' => 66,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 18667818,
                'sit_revista' => 'TITULAR',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            66 => 
            array (
                'id' => 67,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 24577800,
                'sit_revista' => 'PROVISIONAL',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            67 => 
            array (
                'id' => 68,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 16487818,
                'sit_revista' => 'TITULAR',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            68 => 
            array (
                'id' => 69,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 16487818,
                'sit_revista' => 'PROVISIONAL',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            69 => 
            array (
                'id' => 70,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 25934500,
                'sit_revista' => 'PROVISIONAL',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            70 => 
            array (
                'id' => 71,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 24958900,
                'sit_revista' => 'PROVISIONAL',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            71 => 
            array (
                'id' => 72,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 25443400,
                'sit_revista' => 'PROVISIONAL',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            72 => 
            array (
                'id' => 73,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 26681200,
                'sit_revista' => 'PROV/TIT',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            73 => 
            array (
                'id' => 74,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 27815600,
                'sit_revista' => 'PROVISIONAL',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            74 => 
            array (
                'id' => 75,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 24186718,
                'sit_revista' => 'PROVISIONAL',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            75 => 
            array (
                'id' => 76,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 24305600,
                'sit_revista' => 'PROVISIONAL',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            76 => 
            array (
                'id' => 77,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 27816700,
                'sit_revista' => 'PROVISIONAL',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            77 => 
            array (
                'id' => 78,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 5,
                'fecha_fin' => NULL,
                'legajo_prof' => 27208900,
                'sit_revista' => 'PROVISIONAL',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            78 => 
            array (
                'id' => 79,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 27786718,
                'sit_revista' => 'PROVISIONAL',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            79 => 
            array (
                'id' => 80,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 20814500,
                'sit_revista' => 'TITULAR',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            80 => 
            array (
                'id' => 81,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 20814500,
                'sit_revista' => 'SUPLENTE',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            81 => 
            array (
                'id' => 82,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 21442300,
                'sit_revista' => 'TITULAR',
                'observacion' => 'LICENCIA HST 23/12/2022',
                'descripcion' => NULL,
            ),
            82 => 
            array (
                'id' => 83,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 18259000,
                'sit_revista' => 'TITULAR',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            83 => 
            array (
                'id' => 84,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 27735600,
                'sit_revista' => 'PROVISIONAL',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            84 => 
            array (
                'id' => 85,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 28661200,
                'sit_revista' => 'PROVISIONAL',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            85 => 
            array (
                'id' => 86,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 257801,
                'sit_revista' => 'PROVISIONAL',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            86 => 
            array (
                'id' => 87,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 6,
                'fecha_fin' => NULL,
                'legajo_prof' => 257801,
                'sit_revista' => 'PROVISIONAL',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            87 => 
            array (
                'id' => 88,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 6,
                'fecha_fin' => NULL,
                'legajo_prof' => 257801,
                'sit_revista' => 'SUPLENTE',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            88 => 
            array (
                'id' => 89,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 29142300,
                'sit_revista' => 'PROVISIONAL',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            89 => 
            array (
                'id' => 90,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 28727800,
                'sit_revista' => 'PROVISIONAL',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            90 => 
            array (
                'id' => 91,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 28619000,
                'sit_revista' => 'PROVISIONAL',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            91 => 
            array (
                'id' => 92,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 28619000,
                'sit_revista' => 'SUPLENTE',
                'observacion' => 'POR SIGNORELLI',
                'descripcion' => NULL,
            ),
            92 => 
            array (
                'id' => 93,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 26683400,
                'sit_revista' => 'PROVISIONAL',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            93 => 
            array (
                'id' => 94,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 17262300,
                'sit_revista' => 'PROVISIONAL',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            94 => 
            array (
                'id' => 95,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 17262300,
                'sit_revista' => 'SUPLENTE',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            95 => 
            array (
                'id' => 96,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 23508143,
                'sit_revista' => 'SUPLENTE',
                'observacion' => 'POR FAVALORO',
                'descripcion' => NULL,
            ),
            96 => 
            array (
                'id' => 97,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 30641400,
                'sit_revista' => 'SUPLENTE',
                'observacion' => 'POR MELICCHO',
                'descripcion' => NULL,
            ),
            97 => 
            array (
                'id' => 98,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 26021200,
                'sit_revista' => 'SUPLENTE',
                'observacion' => 'POR FAVALORO',
                'descripcion' => NULL,
            ),
            98 => 
            array (
                'id' => 99,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 29438900,
                'sit_revista' => 'SUPLENTE',
                'observacion' => 'POR SOARES DIQUECH',
                'descripcion' => NULL,
            ),
            99 => 
            array (
                'id' => 100,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 21608900,
                'sit_revista' => 'SUPLENTE',
                'observacion' => 'POR FAVALORO',
                'descripcion' => NULL,
            ),
            100 => 
            array (
                'id' => 101,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 7,
                'fecha_fin' => NULL,
                'legajo_prof' => 25590100,
                'sit_revista' => 'SUPLENTE',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            101 => 
            array (
                'id' => 102,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 28725600,
                'sit_revista' => 'PROVISIONAL',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            102 => 
            array (
                'id' => 103,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 23043400,
                'sit_revista' => 'SUPLENTE',
                'observacion' => 'POR MELICCHIO',
                'descripcion' => NULL,
            ),
            103 => 
            array (
                'id' => 104,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 193212,
                'sit_revista' => 'SUPLENTE',
                'observacion' => 'POR SIGNORELLI',
                'descripcion' => NULL,
            ),
            104 => 
            array (
                'id' => 105,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 5,
                'fecha_fin' => NULL,
                'legajo_prof' => 25767800,
                'sit_revista' => 'TITULAR',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            105 => 
            array (
                'id' => 106,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 5,
                'fecha_fin' => NULL,
                'legajo_prof' => 156401,
                'sit_revista' => 'TITULAR',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            106 => 
            array (
                'id' => 107,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 30755500,
                'sit_revista' => 'SUPLENTE',
                'observacion' => 'POR MELICCHIO',
                'descripcion' => NULL,
            ),
            107 => 
            array (
                'id' => 108,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 25440100,
                'sit_revista' => 'PROVISIONAL',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            108 => 
            array (
                'id' => 109,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 30761100,
                'sit_revista' => 'SUPLENTE',
                'observacion' => 'POR MELICCHIO',
                'descripcion' => NULL,
            ),
            109 => 
            array (
                'id' => 110,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 8,
                'fecha_fin' => NULL,
                'legajo_prof' => 26051218,
                'sit_revista' => 'PROVISIONAL',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            110 => 
            array (
                'id' => 111,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 27925600,
                'sit_revista' => 'SUPLENTE',
                'observacion' => 'BAJA DESDE 5/12 POR PIZZI',
                'descripcion' => NULL,
            ),
            111 => 
            array (
                'id' => 112,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 307484000,
                'sit_revista' => 'PROVISIONAL',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            112 => 
            array (
                'id' => 113,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 30767400,
                'sit_revista' => 'PROVISIONAL',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            113 => 
            array (
                'id' => 114,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 30775100,
                'sit_revista' => 'SUPLENTE',
                'observacion' => 'POR  MELICCHIO',
                'descripcion' => NULL,
            ),
            114 => 
            array (
                'id' => 115,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 25473400,
                'sit_revista' => 'SUPLENTE',
                'observacion' => 'BAJA DSD 16/12/2022 POR VARRICA',
                'descripcion' => NULL,
            ),
            115 => 
            array (
                'id' => 116,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 5,
                'fecha_fin' => NULL,
                'legajo_prof' => 155990,
                'sit_revista' => 'SUPLENTE',
                'observacion' => 'POR OVELAR',
                'descripcion' => NULL,
            ),
            116 => 
            array (
                'id' => 117,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 5,
                'fecha_fin' => NULL,
                'legajo_prof' => 24831200,
                'sit_revista' => 'SUPLENTE',
                'observacion' => 'POR TAPIA BAJA EL 31/12/2022',
                'descripcion' => NULL,
            ),
            117 => 
            array (
                'id' => 118,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 30775000,
                'sit_revista' => 'SUPLENTE',
                'observacion' => 'BAJA DESDE EL 16/12 POR VARRICA',
                'descripcion' => NULL,
            ),
            118 => 
            array (
                'id' => 119,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 27776700,
                'sit_revista' => 'SUPLENTE',
                'observacion' => 'POR GABUSI',
                'descripcion' => NULL,
            ),
            119 => 
            array (
                'id' => 120,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 10,
                'fecha_fin' => NULL,
                'legajo_prof' => 1518900,
                'sit_revista' => 'PERMANENTE',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            120 => 
            array (
                'id' => 121,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 10,
                'fecha_fin' => NULL,
                'legajo_prof' => 190238,
                'sit_revista' => 'PERMANENTE',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            121 => 
            array (
                'id' => 122,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 10,
                'fecha_fin' => NULL,
                'legajo_prof' => 25817800,
                'sit_revista' => 'PERMANENTE',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            122 => 
            array (
                'id' => 123,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 12,
                'fecha_fin' => NULL,
                'legajo_prof' => 17106700,
                'sit_revista' => 'PERMANENTE',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            123 => 
            array (
                'id' => 124,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 13,
                'fecha_fin' => NULL,
                'legajo_prof' => 283589,
                'sit_revista' => 'PERMANENTE',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            124 => 
            array (
                'id' => 125,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 11,
                'fecha_fin' => NULL,
                'legajo_prof' => 236845,
                'sit_revista' => 'PERMANENTE',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            125 => 
            array (
                'id' => 126,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 10,
                'fecha_fin' => NULL,
                'legajo_prof' => 231356,
                'sit_revista' => 'PERMANENTE',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            126 => 
            array (
                'id' => 127,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 10,
                'fecha_fin' => NULL,
                'legajo_prof' => 6881700,
                'sit_revista' => 'PERMANENTE',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            127 => 
            array (
                'id' => 128,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 10,
                'fecha_fin' => NULL,
                'legajo_prof' => 6881700,
                'sit_revista' => 'PERMANENTE',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            128 => 
            array (
                'id' => 129,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 10,
                'fecha_fin' => NULL,
                'legajo_prof' => 15190100,
                'sit_revista' => 'PERMANENTE',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            129 => 
            array (
                'id' => 130,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 10,
                'fecha_fin' => NULL,
                'legajo_prof' => 250634,
                'sit_revista' => 'PERMANENTE',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            130 => 
            array (
                'id' => 131,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 10,
                'fecha_fin' => NULL,
                'legajo_prof' => 20314500,
                'sit_revista' => 'PERMANENTE',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            131 => 
            array (
                'id' => 132,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 10,
                'fecha_fin' => NULL,
                'legajo_prof' => 307363,
                'sit_revista' => 'TEMPORARIO',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            132 => 
            array (
                'id' => 133,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 10,
                'fecha_fin' => NULL,
                'legajo_prof' => 307504,
                'sit_revista' => 'TEMPORARIO',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            133 => 
            array (
                'id' => 134,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 20769000,
                'sit_revista' => 'PROV/TIT',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            134 => 
            array (
                'id' => 135,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 24577800,
                'sit_revista' => 'PROV/TIT',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            135 => 
            array (
                'id' => 136,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 24958900,
                'sit_revista' => 'PROV/TIT',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            136 => 
            array (
                'id' => 137,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 24305600,
                'sit_revista' => 'PROV/TIT',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            137 => 
            array (
                'id' => 138,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 30775100,
                'sit_revista' => 'SUPLENTE',
                'observacion' => 'POR  D´AQUINO',
                'descripcion' => 'PDAQUINO',
            ),
            138 => 
            array (
                'id' => 139,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 17868918,
                'sit_revista' => 'TITULAR',
                'observacion' => NULL,
                'descripcion' => 'pTitHC2',
            ),
            139 => 
            array (
                'id' => 140,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 19887800,
                'sit_revista' => 'PROVISIONAL',
                'observacion' => NULL,
                'descripcion' => 'pProHC2',
            ),
            140 => 
            array (
                'id' => 141,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 186401,
                'sit_revista' => 'TITULAR',
                'observacion' => NULL,
                'descripcion' => 'pTitHC2',
            ),
            141 => 
            array (
                'id' => 142,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 20808900,
                'sit_revista' => 'TITULAR',
                'observacion' => NULL,
                'descripcion' => 'pTitHC2',
            ),
            142 => 
            array (
                'id' => 143,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 8,
                'fecha_fin' => NULL,
                'legajo_prof' => 20770118,
                'sit_revista' => 'PROVISIONAL',
                'observacion' => NULL,
                'descripcion' => NULL,
            ),
            143 => 
            array (
                'id' => 144,
                'baja' => 0,
                'created_at' => '2023-01-28 03:33:56',
                'updated_at' => NULL,
                'id_rol' => 4,
                'fecha_fin' => NULL,
                'legajo_prof' => 18667818,
                'sit_revista' => 'TITULAR',
                'observacion' => 'LICENCIA 6HSCAT HST 20/128/2022',
                'descripcion' => 'pTitHC2',
            ),
        ));
        
        
    }
}