<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
class RolXProfesorSemTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        DB::table('rol_x_profesor_sem')->delete();
        
        DB::table('rol_x_profesor_sem')->insert(array (
            0 => 
            array (
                'id' => 1,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 1,
                'lunes' => 0,
                'martes' => 0,
                'miercoles' => 0,
                'jueves' => 0,
                'viernes' => 0,
                'sabado' => 1,
            ),
            1 => 
            array (
                'id' => 2,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 2,
                'lunes' => 0,
                'martes' => 0,
                'miercoles' => 0,
                'jueves' => 0,
                'viernes' => 0,
                'sabado' => 1,
            ),
            2 => 
            array (
                'id' => 3,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 3,
                'lunes' => 0,
                'martes' => 0,
                'miercoles' => 0,
                'jueves' => 0,
                'viernes' => 0,
                'sabado' => 1,
            ),
            3 => 
            array (
                'id' => 4,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 4,
                'lunes' => 0,
                'martes' => 0,
                'miercoles' => 0,
                'jueves' => 0,
                'viernes' => 0,
                'sabado' => 1,
            ),
            4 => 
            array (
                'id' => 5,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 5,
                'lunes' => 0,
                'martes' => 0,
                'miercoles' => 0,
                'jueves' => 0,
                'viernes' => 1,
                'sabado' => 1,
            ),
            5 => 
            array (
                'id' => 6,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 6,
                'lunes' => 0,
                'martes' => 0,
                'miercoles' => 0,
                'jueves' => 0,
                'viernes' => 1,
                'sabado' => 1,
            ),
            6 => 
            array (
                'id' => 7,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 7,
                'lunes' => 1,
                'martes' => 0,
                'miercoles' => 1,
                'jueves' => 1,
                'viernes' => 1,
                'sabado' => 1,
            ),
            7 => 
            array (
                'id' => 8,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 8,
                'lunes' => 0,
                'martes' => 0,
                'miercoles' => 0,
                'jueves' => 0,
                'viernes' => 1,
                'sabado' => 1,
            ),
            8 => 
            array (
                'id' => 9,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 9,
                'lunes' => 0,
                'martes' => 0,
                'miercoles' => 0,
                'jueves' => 0,
                'viernes' => 0,
                'sabado' => 1,
            ),
            9 => 
            array (
                'id' => 10,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 10,
                'lunes' => 0,
                'martes' => 0,
                'miercoles' => 0,
                'jueves' => 0,
                'viernes' => 0,
                'sabado' => 1,
            ),
            10 => 
            array (
                'id' => 11,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 11,
                'lunes' => 0,
                'martes' => 0,
                'miercoles' => 0,
                'jueves' => 0,
                'viernes' => 1,
                'sabado' => 1,
            ),
            11 => 
            array (
                'id' => 12,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 12,
                'lunes' => 0,
                'martes' => 0,
                'miercoles' => 0,
                'jueves' => 0,
                'viernes' => 1,
                'sabado' => 1,
            ),
            12 => 
            array (
                'id' => 13,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 13,
                'lunes' => 1,
                'martes' => 1,
                'miercoles' => 1,
                'jueves' => 1,
                'viernes' => 1,
                'sabado' => 1,
            ),
            13 => 
            array (
                'id' => 14,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 14,
                'lunes' => 0,
                'martes' => 1,
                'miercoles' => 0,
                'jueves' => 0,
                'viernes' => 0,
                'sabado' => 1,
            ),
            14 => 
            array (
                'id' => 15,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 15,
                'lunes' => 0,
                'martes' => 1,
                'miercoles' => 0,
                'jueves' => 0,
                'viernes' => 0,
                'sabado' => 1,
            ),
            15 => 
            array (
                'id' => 16,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 16,
                'lunes' => 1,
                'martes' => 0,
                'miercoles' => 1,
                'jueves' => 0,
                'viernes' => 1,
                'sabado' => 1,
            ),
            16 => 
            array (
                'id' => 17,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 17,
                'lunes' => 1,
                'martes' => 0,
                'miercoles' => 1,
                'jueves' => 1,
                'viernes' => 1,
                'sabado' => 1,
            ),
            17 => 
            array (
                'id' => 18,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 18,
                'lunes' => 1,
                'martes' => 1,
                'miercoles' => 0,
                'jueves' => 1,
                'viernes' => 1,
                'sabado' => 1,
            ),
            18 => 
            array (
                'id' => 19,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 19,
                'lunes' => 0,
                'martes' => 0,
                'miercoles' => 0,
                'jueves' => 0,
                'viernes' => 0,
                'sabado' => 1,
            ),
            19 => 
            array (
                'id' => 20,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 20,
                'lunes' => 1,
                'martes' => 0,
                'miercoles' => 1,
                'jueves' => 0,
                'viernes' => 0,
                'sabado' => 1,
            ),
            20 => 
            array (
                'id' => 21,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 21,
                'lunes' => 1,
                'martes' => 0,
                'miercoles' => 1,
                'jueves' => 0,
                'viernes' => 0,
                'sabado' => 1,
            ),
            21 => 
            array (
                'id' => 22,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 22,
                'lunes' => 0,
                'martes' => 1,
                'miercoles' => 0,
                'jueves' => 1,
                'viernes' => 0,
                'sabado' => 1,
            ),
            22 => 
            array (
                'id' => 23,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 23,
                'lunes' => 1,
                'martes' => 1,
                'miercoles' => 0,
                'jueves' => 1,
                'viernes' => 1,
                'sabado' => 1,
            ),
            23 => 
            array (
                'id' => 24,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 24,
                'lunes' => 0,
                'martes' => 0,
                'miercoles' => 0,
                'jueves' => 0,
                'viernes' => 0,
                'sabado' => 1,
            ),
            24 => 
            array (
                'id' => 25,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 25,
                'lunes' => 0,
                'martes' => 0,
                'miercoles' => 0,
                'jueves' => 0,
                'viernes' => 0,
                'sabado' => 1,
            ),
            25 => 
            array (
                'id' => 26,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 26,
                'lunes' => 1,
                'martes' => 0,
                'miercoles' => 1,
                'jueves' => 0,
                'viernes' => 1,
                'sabado' => 1,
            ),
            26 => 
            array (
                'id' => 27,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 27,
                'lunes' => 0,
                'martes' => 0,
                'miercoles' => 0,
                'jueves' => 0,
                'viernes' => 0,
                'sabado' => 1,
            ),
            27 => 
            array (
                'id' => 28,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 28,
                'lunes' => 0,
                'martes' => 0,
                'miercoles' => 0,
                'jueves' => 0,
                'viernes' => 1,
                'sabado' => 1,
            ),
            28 => 
            array (
                'id' => 29,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 29,
                'lunes' => 0,
                'martes' => 1,
                'miercoles' => 0,
                'jueves' => 0,
                'viernes' => 0,
                'sabado' => 1,
            ),
            29 => 
            array (
                'id' => 30,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 30,
                'lunes' => 0,
                'martes' => 0,
                'miercoles' => 0,
                'jueves' => 0,
                'viernes' => 0,
                'sabado' => 1,
            ),
            30 => 
            array (
                'id' => 31,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 31,
                'lunes' => 0,
                'martes' => 0,
                'miercoles' => 0,
                'jueves' => 0,
                'viernes' => 0,
                'sabado' => 1,
            ),
            31 => 
            array (
                'id' => 32,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 32,
                'lunes' => 0,
                'martes' => 1,
                'miercoles' => 1,
                'jueves' => 1,
                'viernes' => 0,
                'sabado' => 1,
            ),
            32 => 
            array (
                'id' => 33,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 33,
                'lunes' => 0,
                'martes' => 0,
                'miercoles' => 0,
                'jueves' => 0,
                'viernes' => 0,
                'sabado' => 1,
            ),
            33 => 
            array (
                'id' => 34,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 34,
                'lunes' => 0,
                'martes' => 0,
                'miercoles' => 0,
                'jueves' => 0,
                'viernes' => 0,
                'sabado' => 1,
            ),
            34 => 
            array (
                'id' => 35,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 35,
                'lunes' => 1,
                'martes' => 0,
                'miercoles' => 1,
                'jueves' => 0,
                'viernes' => 1,
                'sabado' => 1,
            ),
            35 => 
            array (
                'id' => 36,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 36,
                'lunes' => 0,
                'martes' => 0,
                'miercoles' => 0,
                'jueves' => 0,
                'viernes' => 0,
                'sabado' => 1,
            ),
            36 => 
            array (
                'id' => 37,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 37,
                'lunes' => 1,
                'martes' => 1,
                'miercoles' => 1,
                'jueves' => 1,
                'viernes' => 0,
                'sabado' => 1,
            ),
            37 => 
            array (
                'id' => 38,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 38,
                'lunes' => 1,
                'martes' => 1,
                'miercoles' => 1,
                'jueves' => 1,
                'viernes' => 0,
                'sabado' => 1,
            ),
            38 => 
            array (
                'id' => 39,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 39,
                'lunes' => 1,
                'martes' => 0,
                'miercoles' => 1,
                'jueves' => 1,
                'viernes' => 1,
                'sabado' => 1,
            ),
            39 => 
            array (
                'id' => 40,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 40,
                'lunes' => 1,
                'martes' => 0,
                'miercoles' => 1,
                'jueves' => 0,
                'viernes' => 1,
                'sabado' => 1,
            ),
            40 => 
            array (
                'id' => 41,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 41,
                'lunes' => 1,
                'martes' => 0,
                'miercoles' => 1,
                'jueves' => 0,
                'viernes' => 0,
                'sabado' => 1,
            ),
            41 => 
            array (
                'id' => 42,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 42,
                'lunes' => 0,
                'martes' => 0,
                'miercoles' => 0,
                'jueves' => 0,
                'viernes' => 0,
                'sabado' => 1,
            ),
            42 => 
            array (
                'id' => 43,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 43,
                'lunes' => 1,
                'martes' => 0,
                'miercoles' => 0,
                'jueves' => 0,
                'viernes' => 0,
                'sabado' => 1,
            ),
            43 => 
            array (
                'id' => 44,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 44,
                'lunes' => 0,
                'martes' => 0,
                'miercoles' => 1,
                'jueves' => 0,
                'viernes' => 1,
                'sabado' => 1,
            ),
            44 => 
            array (
                'id' => 45,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 45,
                'lunes' => 1,
                'martes' => 1,
                'miercoles' => 1,
                'jueves' => 1,
                'viernes' => 0,
                'sabado' => 1,
            ),
            45 => 
            array (
                'id' => 46,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 46,
                'lunes' => 1,
                'martes' => 1,
                'miercoles' => 0,
                'jueves' => 1,
                'viernes' => 0,
                'sabado' => 1,
            ),
            46 => 
            array (
                'id' => 47,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 47,
                'lunes' => 1,
                'martes' => 0,
                'miercoles' => 1,
                'jueves' => 0,
                'viernes' => 0,
                'sabado' => 1,
            ),
            47 => 
            array (
                'id' => 48,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 48,
                'lunes' => 1,
                'martes' => 1,
                'miercoles' => 1,
                'jueves' => 0,
                'viernes' => 0,
                'sabado' => 1,
            ),
            48 => 
            array (
                'id' => 49,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 49,
                'lunes' => 0,
                'martes' => 1,
                'miercoles' => 0,
                'jueves' => 0,
                'viernes' => 0,
                'sabado' => 1,
            ),
            49 => 
            array (
                'id' => 50,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 50,
                'lunes' => 1,
                'martes' => 1,
                'miercoles' => 0,
                'jueves' => 0,
                'viernes' => 0,
                'sabado' => 1,
            ),
            50 => 
            array (
                'id' => 51,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 134,
                'lunes' => 0,
                'martes' => 1,
                'miercoles' => 0,
                'jueves' => 0,
                'viernes' => 0,
                'sabado' => 1,
            ),
            51 => 
            array (
                'id' => 52,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 51,
                'lunes' => 0,
                'martes' => 0,
                'miercoles' => 1,
                'jueves' => 1,
                'viernes' => 0,
                'sabado' => 1,
            ),
            52 => 
            array (
                'id' => 53,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 52,
                'lunes' => 0,
                'martes' => 0,
                'miercoles' => 1,
                'jueves' => 1,
                'viernes' => 0,
                'sabado' => 1,
            ),
            53 => 
            array (
                'id' => 54,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 53,
                'lunes' => 1,
                'martes' => 0,
                'miercoles' => 1,
                'jueves' => 0,
                'viernes' => 1,
                'sabado' => 1,
            ),
            54 => 
            array (
                'id' => 55,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 54,
                'lunes' => 0,
                'martes' => 1,
                'miercoles' => 1,
                'jueves' => 0,
                'viernes' => 0,
                'sabado' => 1,
            ),
            55 => 
            array (
                'id' => 56,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 55,
                'lunes' => 0,
                'martes' => 1,
                'miercoles' => 1,
                'jueves' => 0,
                'viernes' => 0,
                'sabado' => 1,
            ),
            56 => 
            array (
                'id' => 57,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 56,
                'lunes' => 1,
                'martes' => 1,
                'miercoles' => 0,
                'jueves' => 1,
                'viernes' => 1,
                'sabado' => 1,
            ),
            57 => 
            array (
                'id' => 58,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 57,
                'lunes' => 0,
                'martes' => 0,
                'miercoles' => 0,
                'jueves' => 0,
                'viernes' => 0,
                'sabado' => 1,
            ),
            58 => 
            array (
                'id' => 59,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 58,
                'lunes' => 0,
                'martes' => 0,
                'miercoles' => 0,
                'jueves' => 0,
                'viernes' => 0,
                'sabado' => 1,
            ),
            59 => 
            array (
                'id' => 60,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 59,
                'lunes' => 0,
                'martes' => 0,
                'miercoles' => 0,
                'jueves' => 0,
                'viernes' => 0,
                'sabado' => 1,
            ),
            60 => 
            array (
                'id' => 61,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 60,
                'lunes' => 0,
                'martes' => 0,
                'miercoles' => 0,
                'jueves' => 0,
                'viernes' => 0,
                'sabado' => 1,
            ),
            61 => 
            array (
                'id' => 62,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 61,
                'lunes' => 0,
                'martes' => 1,
                'miercoles' => 0,
                'jueves' => 1,
                'viernes' => 1,
                'sabado' => 1,
            ),
            62 => 
            array (
                'id' => 63,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 62,
                'lunes' => 0,
                'martes' => 1,
                'miercoles' => 0,
                'jueves' => 1,
                'viernes' => 0,
                'sabado' => 1,
            ),
            63 => 
            array (
                'id' => 64,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 63,
                'lunes' => 1,
                'martes' => 0,
                'miercoles' => 1,
                'jueves' => 0,
                'viernes' => 1,
                'sabado' => 1,
            ),
            64 => 
            array (
                'id' => 65,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 64,
                'lunes' => 0,
                'martes' => 0,
                'miercoles' => 0,
                'jueves' => 0,
                'viernes' => 0,
                'sabado' => 1,
            ),
            65 => 
            array (
                'id' => 66,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 65,
                'lunes' => 1,
                'martes' => 1,
                'miercoles' => 1,
                'jueves' => 0,
                'viernes' => 1,
                'sabado' => 1,
            ),
            66 => 
            array (
                'id' => 67,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 66,
                'lunes' => 0,
                'martes' => 0,
                'miercoles' => 0,
                'jueves' => 0,
                'viernes' => 0,
                'sabado' => 1,
            ),
            67 => 
            array (
                'id' => 68,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 67,
                'lunes' => 0,
                'martes' => 0,
                'miercoles' => 1,
                'jueves' => 0,
                'viernes' => 0,
                'sabado' => 1,
            ),
            68 => 
            array (
                'id' => 69,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 135,
                'lunes' => 0,
                'martes' => 0,
                'miercoles' => 1,
                'jueves' => 0,
                'viernes' => 0,
                'sabado' => 1,
            ),
            69 => 
            array (
                'id' => 70,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 68,
                'lunes' => 0,
                'martes' => 0,
                'miercoles' => 0,
                'jueves' => 0,
                'viernes' => 0,
                'sabado' => 1,
            ),
            70 => 
            array (
                'id' => 71,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 69,
                'lunes' => 0,
                'martes' => 0,
                'miercoles' => 0,
                'jueves' => 0,
                'viernes' => 0,
                'sabado' => 1,
            ),
            71 => 
            array (
                'id' => 72,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 70,
                'lunes' => 1,
                'martes' => 0,
                'miercoles' => 1,
                'jueves' => 0,
                'viernes' => 1,
                'sabado' => 1,
            ),
            72 => 
            array (
                'id' => 73,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 71,
                'lunes' => 1,
                'martes' => 1,
                'miercoles' => 0,
                'jueves' => 1,
                'viernes' => 1,
                'sabado' => 1,
            ),
            73 => 
            array (
                'id' => 74,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 136,
                'lunes' => 1,
                'martes' => 0,
                'miercoles' => 1,
                'jueves' => 1,
                'viernes' => 1,
                'sabado' => 1,
            ),
            74 => 
            array (
                'id' => 75,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 72,
                'lunes' => 0,
                'martes' => 1,
                'miercoles' => 1,
                'jueves' => 1,
                'viernes' => 1,
                'sabado' => 1,
            ),
            75 => 
            array (
                'id' => 76,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 73,
                'lunes' => 1,
                'martes' => 0,
                'miercoles' => 1,
                'jueves' => 1,
                'viernes' => 1,
                'sabado' => 1,
            ),
            76 => 
            array (
                'id' => 77,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 74,
                'lunes' => 1,
                'martes' => 1,
                'miercoles' => 1,
                'jueves' => 1,
                'viernes' => 1,
                'sabado' => 1,
            ),
            77 => 
            array (
                'id' => 78,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 75,
                'lunes' => 1,
                'martes' => 0,
                'miercoles' => 0,
                'jueves' => 1,
                'viernes' => 1,
                'sabado' => 1,
            ),
            78 => 
            array (
                'id' => 79,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 76,
                'lunes' => 1,
                'martes' => 1,
                'miercoles' => 1,
                'jueves' => 1,
                'viernes' => 0,
                'sabado' => 1,
            ),
            79 => 
            array (
                'id' => 80,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 137,
                'lunes' => 1,
                'martes' => 1,
                'miercoles' => 1,
                'jueves' => 1,
                'viernes' => 0,
                'sabado' => 1,
            ),
            80 => 
            array (
                'id' => 81,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 77,
                'lunes' => 1,
                'martes' => 1,
                'miercoles' => 1,
                'jueves' => 1,
                'viernes' => 1,
                'sabado' => 1,
            ),
            81 => 
            array (
                'id' => 82,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 78,
                'lunes' => 0,
                'martes' => 0,
                'miercoles' => 0,
                'jueves' => 0,
                'viernes' => 0,
                'sabado' => 1,
            ),
            82 => 
            array (
                'id' => 83,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 79,
                'lunes' => 1,
                'martes' => 1,
                'miercoles' => 0,
                'jueves' => 0,
                'viernes' => 1,
                'sabado' => 1,
            ),
            83 => 
            array (
                'id' => 84,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 80,
                'lunes' => 1,
                'martes' => 1,
                'miercoles' => 0,
                'jueves' => 1,
                'viernes' => 1,
                'sabado' => 1,
            ),
            84 => 
            array (
                'id' => 85,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 81,
                'lunes' => 1,
                'martes' => 1,
                'miercoles' => 1,
                'jueves' => 1,
                'viernes' => 1,
                'sabado' => 1,
            ),
            85 => 
            array (
                'id' => 86,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 82,
                'lunes' => 1,
                'martes' => 0,
                'miercoles' => 1,
                'jueves' => 1,
                'viernes' => 1,
                'sabado' => 1,
            ),
            86 => 
            array (
                'id' => 87,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 83,
                'lunes' => 1,
                'martes' => 1,
                'miercoles' => 1,
                'jueves' => 1,
                'viernes' => 0,
                'sabado' => 1,
            ),
            87 => 
            array (
                'id' => 88,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 84,
                'lunes' => 0,
                'martes' => 1,
                'miercoles' => 1,
                'jueves' => 1,
                'viernes' => 1,
                'sabado' => 1,
            ),
            88 => 
            array (
                'id' => 89,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 85,
                'lunes' => 1,
                'martes' => 1,
                'miercoles' => 0,
                'jueves' => 1,
                'viernes' => 1,
                'sabado' => 1,
            ),
            89 => 
            array (
                'id' => 90,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:47',
                'updated_at' => NULL,
                'id_rol_prof' => 86,
                'lunes' => 1,
                'martes' => 1,
                'miercoles' => 1,
                'jueves' => 0,
                'viernes' => 1,
                'sabado' => 1,
            ),
            90 => 
            array (
                'id' => 91,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:48',
                'updated_at' => NULL,
                'id_rol_prof' => 87,
                'lunes' => 1,
                'martes' => 1,
                'miercoles' => 0,
                'jueves' => 1,
                'viernes' => 1,
                'sabado' => 1,
            ),
            91 => 
            array (
                'id' => 92,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:48',
                'updated_at' => NULL,
                'id_rol_prof' => 88,
                'lunes' => 0,
                'martes' => 0,
                'miercoles' => 0,
                'jueves' => 0,
                'viernes' => 0,
                'sabado' => 1,
            ),
            92 => 
            array (
                'id' => 93,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:48',
                'updated_at' => NULL,
                'id_rol_prof' => 89,
                'lunes' => 1,
                'martes' => 1,
                'miercoles' => 0,
                'jueves' => 1,
                'viernes' => 1,
                'sabado' => 1,
            ),
            93 => 
            array (
                'id' => 94,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:48',
                'updated_at' => NULL,
                'id_rol_prof' => 90,
                'lunes' => 1,
                'martes' => 1,
                'miercoles' => 1,
                'jueves' => 1,
                'viernes' => 1,
                'sabado' => 1,
            ),
            94 => 
            array (
                'id' => 95,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:48',
                'updated_at' => NULL,
                'id_rol_prof' => 91,
                'lunes' => 1,
                'martes' => 1,
                'miercoles' => 0,
                'jueves' => 1,
                'viernes' => 1,
                'sabado' => 1,
            ),
            95 => 
            array (
                'id' => 96,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:48',
                'updated_at' => NULL,
                'id_rol_prof' => 92,
                'lunes' => 0,
                'martes' => 0,
                'miercoles' => 1,
                'jueves' => 1,
                'viernes' => 1,
                'sabado' => 1,
            ),
            96 => 
            array (
                'id' => 97,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:48',
                'updated_at' => NULL,
                'id_rol_prof' => 93,
                'lunes' => 1,
                'martes' => 1,
                'miercoles' => 1,
                'jueves' => 0,
                'viernes' => 1,
                'sabado' => 1,
            ),
            97 => 
            array (
                'id' => 98,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:48',
                'updated_at' => NULL,
                'id_rol_prof' => 94,
                'lunes' => 0,
                'martes' => 1,
                'miercoles' => 0,
                'jueves' => 1,
                'viernes' => 1,
                'sabado' => 1,
            ),
            98 => 
            array (
                'id' => 99,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:48',
                'updated_at' => NULL,
                'id_rol_prof' => 95,
                'lunes' => 1,
                'martes' => 1,
                'miercoles' => 0,
                'jueves' => 1,
                'viernes' => 1,
                'sabado' => 1,
            ),
            99 => 
            array (
                'id' => 100,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:48',
                'updated_at' => NULL,
                'id_rol_prof' => 96,
                'lunes' => 1,
                'martes' => 1,
                'miercoles' => 1,
                'jueves' => 1,
                'viernes' => 1,
                'sabado' => 1,
            ),
            100 => 
            array (
                'id' => 101,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:48',
                'updated_at' => NULL,
                'id_rol_prof' => 97,
                'lunes' => 1,
                'martes' => 1,
                'miercoles' => 1,
                'jueves' => 1,
                'viernes' => 1,
                'sabado' => 1,
            ),
            101 => 
            array (
                'id' => 102,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:48',
                'updated_at' => NULL,
                'id_rol_prof' => 98,
                'lunes' => 1,
                'martes' => 1,
                'miercoles' => 1,
                'jueves' => 1,
                'viernes' => 0,
                'sabado' => 1,
            ),
            102 => 
            array (
                'id' => 103,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:48',
                'updated_at' => NULL,
                'id_rol_prof' => 99,
                'lunes' => 1,
                'martes' => 1,
                'miercoles' => 1,
                'jueves' => 1,
                'viernes' => 1,
                'sabado' => 1,
            ),
            103 => 
            array (
                'id' => 104,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:48',
                'updated_at' => NULL,
                'id_rol_prof' => 100,
                'lunes' => 1,
                'martes' => 1,
                'miercoles' => 0,
                'jueves' => 1,
                'viernes' => 1,
                'sabado' => 1,
            ),
            104 => 
            array (
                'id' => 105,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:48',
                'updated_at' => NULL,
                'id_rol_prof' => 101,
                'lunes' => 0,
                'martes' => 0,
                'miercoles' => 0,
                'jueves' => 0,
                'viernes' => 0,
                'sabado' => 1,
            ),
            105 => 
            array (
                'id' => 106,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:48',
                'updated_at' => NULL,
                'id_rol_prof' => 102,
                'lunes' => 1,
                'martes' => 0,
                'miercoles' => 1,
                'jueves' => 1,
                'viernes' => 1,
                'sabado' => 1,
            ),
            106 => 
            array (
                'id' => 107,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:48',
                'updated_at' => NULL,
                'id_rol_prof' => 103,
                'lunes' => 0,
                'martes' => 0,
                'miercoles' => 1,
                'jueves' => 1,
                'viernes' => 1,
                'sabado' => 1,
            ),
            107 => 
            array (
                'id' => 108,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:48',
                'updated_at' => NULL,
                'id_rol_prof' => 104,
                'lunes' => 1,
                'martes' => 0,
                'miercoles' => 1,
                'jueves' => 0,
                'viernes' => 1,
                'sabado' => 1,
            ),
            108 => 
            array (
                'id' => 109,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:48',
                'updated_at' => NULL,
                'id_rol_prof' => 105,
                'lunes' => 1,
                'martes' => 1,
                'miercoles' => 0,
                'jueves' => 1,
                'viernes' => 0,
                'sabado' => 1,
            ),
            109 => 
            array (
                'id' => 110,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:48',
                'updated_at' => NULL,
                'id_rol_prof' => 106,
                'lunes' => 0,
                'martes' => 0,
                'miercoles' => 0,
                'jueves' => 0,
                'viernes' => 0,
                'sabado' => 1,
            ),
            110 => 
            array (
                'id' => 111,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:48',
                'updated_at' => NULL,
                'id_rol_prof' => 107,
                'lunes' => 1,
                'martes' => 0,
                'miercoles' => 1,
                'jueves' => 1,
                'viernes' => 1,
                'sabado' => 1,
            ),
            111 => 
            array (
                'id' => 112,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:48',
                'updated_at' => NULL,
                'id_rol_prof' => 108,
                'lunes' => 1,
                'martes' => 0,
                'miercoles' => 1,
                'jueves' => 0,
                'viernes' => 0,
                'sabado' => 1,
            ),
            112 => 
            array (
                'id' => 113,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:48',
                'updated_at' => NULL,
                'id_rol_prof' => 109,
                'lunes' => 1,
                'martes' => 1,
                'miercoles' => 0,
                'jueves' => 1,
                'viernes' => 1,
                'sabado' => 1,
            ),
            113 => 
            array (
                'id' => 114,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:48',
                'updated_at' => NULL,
                'id_rol_prof' => 110,
                'lunes' => 1,
                'martes' => 0,
                'miercoles' => 1,
                'jueves' => 1,
                'viernes' => 1,
                'sabado' => 1,
            ),
            114 => 
            array (
                'id' => 115,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:48',
                'updated_at' => NULL,
                'id_rol_prof' => 111,
                'lunes' => 1,
                'martes' => 0,
                'miercoles' => 1,
                'jueves' => 1,
                'viernes' => 1,
                'sabado' => 1,
            ),
            115 => 
            array (
                'id' => 116,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:48',
                'updated_at' => NULL,
                'id_rol_prof' => 112,
                'lunes' => 1,
                'martes' => 1,
                'miercoles' => 1,
                'jueves' => 1,
                'viernes' => 1,
                'sabado' => 1,
            ),
            116 => 
            array (
                'id' => 117,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:48',
                'updated_at' => NULL,
                'id_rol_prof' => 113,
                'lunes' => 1,
                'martes' => 1,
                'miercoles' => 1,
                'jueves' => 1,
                'viernes' => 1,
                'sabado' => 1,
            ),
            117 => 
            array (
                'id' => 118,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:48',
                'updated_at' => NULL,
                'id_rol_prof' => 114,
                'lunes' => 0,
                'martes' => 1,
                'miercoles' => 1,
                'jueves' => 1,
                'viernes' => 1,
                'sabado' => 1,
            ),
            118 => 
            array (
                'id' => 119,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:48',
                'updated_at' => NULL,
                'id_rol_prof' => 115,
                'lunes' => 1,
                'martes' => 1,
                'miercoles' => 0,
                'jueves' => 1,
                'viernes' => 1,
                'sabado' => 1,
            ),
            119 => 
            array (
                'id' => 120,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:48',
                'updated_at' => NULL,
                'id_rol_prof' => 116,
                'lunes' => 0,
                'martes' => 0,
                'miercoles' => 0,
                'jueves' => 0,
                'viernes' => 0,
                'sabado' => 1,
            ),
            120 => 
            array (
                'id' => 121,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:48',
                'updated_at' => NULL,
                'id_rol_prof' => 117,
                'lunes' => 0,
                'martes' => 0,
                'miercoles' => 0,
                'jueves' => 0,
                'viernes' => 0,
                'sabado' => 1,
            ),
            121 => 
            array (
                'id' => 122,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:48',
                'updated_at' => NULL,
                'id_rol_prof' => 118,
                'lunes' => 1,
                'martes' => 0,
                'miercoles' => 1,
                'jueves' => 1,
                'viernes' => 1,
                'sabado' => 1,
            ),
            122 => 
            array (
                'id' => 123,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:48',
                'updated_at' => NULL,
                'id_rol_prof' => 119,
                'lunes' => 1,
                'martes' => 1,
                'miercoles' => 0,
                'jueves' => 1,
                'viernes' => 1,
                'sabado' => 1,
            ),
            123 => 
            array (
                'id' => 124,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:48',
                'updated_at' => NULL,
                'id_rol_prof' => 138,
                'lunes' => 1,
                'martes' => 0,
                'miercoles' => 1,
                'jueves' => 0,
                'viernes' => 1,
                'sabado' => 1,
            ),
            124 => 
            array (
                'id' => 125,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:48',
                'updated_at' => NULL,
                'id_rol_prof' => 120,
                'lunes' => 0,
                'martes' => 0,
                'miercoles' => 0,
                'jueves' => 0,
                'viernes' => 0,
                'sabado' => 1,
            ),
            125 => 
            array (
                'id' => 126,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:48',
                'updated_at' => NULL,
                'id_rol_prof' => 121,
                'lunes' => 0,
                'martes' => 0,
                'miercoles' => 0,
                'jueves' => 0,
                'viernes' => 0,
                'sabado' => 1,
            ),
            126 => 
            array (
                'id' => 127,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:48',
                'updated_at' => NULL,
                'id_rol_prof' => 122,
                'lunes' => 0,
                'martes' => 0,
                'miercoles' => 0,
                'jueves' => 0,
                'viernes' => 0,
                'sabado' => 1,
            ),
            127 => 
            array (
                'id' => 128,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:48',
                'updated_at' => NULL,
                'id_rol_prof' => 123,
                'lunes' => 0,
                'martes' => 0,
                'miercoles' => 0,
                'jueves' => 0,
                'viernes' => 0,
                'sabado' => 1,
            ),
            128 => 
            array (
                'id' => 129,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:48',
                'updated_at' => NULL,
                'id_rol_prof' => 124,
                'lunes' => 0,
                'martes' => 0,
                'miercoles' => 0,
                'jueves' => 0,
                'viernes' => 0,
                'sabado' => 1,
            ),
            129 => 
            array (
                'id' => 130,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:48',
                'updated_at' => NULL,
                'id_rol_prof' => 125,
                'lunes' => 1,
                'martes' => 0,
                'miercoles' => 0,
                'jueves' => 0,
                'viernes' => 0,
                'sabado' => 1,
            ),
            130 => 
            array (
                'id' => 131,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:48',
                'updated_at' => NULL,
                'id_rol_prof' => 126,
                'lunes' => 0,
                'martes' => 0,
                'miercoles' => 0,
                'jueves' => 0,
                'viernes' => 0,
                'sabado' => 1,
            ),
            131 => 
            array (
                'id' => 132,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:48',
                'updated_at' => NULL,
                'id_rol_prof' => 127,
                'lunes' => 0,
                'martes' => 0,
                'miercoles' => 0,
                'jueves' => 0,
                'viernes' => 0,
                'sabado' => 1,
            ),
            132 => 
            array (
                'id' => 133,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:48',
                'updated_at' => NULL,
                'id_rol_prof' => 128,
                'lunes' => 0,
                'martes' => 0,
                'miercoles' => 0,
                'jueves' => 0,
                'viernes' => 0,
                'sabado' => 1,
            ),
            133 => 
            array (
                'id' => 134,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:48',
                'updated_at' => NULL,
                'id_rol_prof' => 129,
                'lunes' => 0,
                'martes' => 0,
                'miercoles' => 0,
                'jueves' => 0,
                'viernes' => 0,
                'sabado' => 1,
            ),
            134 => 
            array (
                'id' => 135,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:48',
                'updated_at' => NULL,
                'id_rol_prof' => 130,
                'lunes' => 0,
                'martes' => 0,
                'miercoles' => 0,
                'jueves' => 0,
                'viernes' => 0,
                'sabado' => 1,
            ),
            135 => 
            array (
                'id' => 136,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:48',
                'updated_at' => NULL,
                'id_rol_prof' => 131,
                'lunes' => 0,
                'martes' => 0,
                'miercoles' => 0,
                'jueves' => 0,
                'viernes' => 1,
                'sabado' => 1,
            ),
            136 => 
            array (
                'id' => 137,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:48',
                'updated_at' => NULL,
                'id_rol_prof' => 132,
                'lunes' => 0,
                'martes' => 0,
                'miercoles' => 1,
                'jueves' => 0,
                'viernes' => 0,
                'sabado' => 1,
            ),
            137 => 
            array (
                'id' => 138,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:48',
                'updated_at' => NULL,
                'id_rol_prof' => 133,
                'lunes' => 0,
                'martes' => 0,
                'miercoles' => 0,
                'jueves' => 0,
                'viernes' => 1,
                'sabado' => 1,
            ),
            138 => 
            array (
                'id' => 139,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:48',
                'updated_at' => NULL,
                'id_rol_prof' => 139,
                'lunes' => 0,
                'martes' => 0,
                'miercoles' => 0,
                'jueves' => 0,
                'viernes' => 0,
                'sabado' => 1,
            ),
            139 => 
            array (
                'id' => 140,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:48',
                'updated_at' => NULL,
                'id_rol_prof' => 140,
                'lunes' => 1,
                'martes' => 1,
                'miercoles' => 1,
                'jueves' => 1,
                'viernes' => 1,
                'sabado' => 1,
            ),
            140 => 
            array (
                'id' => 141,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:48',
                'updated_at' => NULL,
                'id_rol_prof' => 141,
                'lunes' => 1,
                'martes' => 1,
                'miercoles' => 0,
                'jueves' => 1,
                'viernes' => 1,
                'sabado' => 1,
            ),
            141 => 
            array (
                'id' => 142,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:48',
                'updated_at' => NULL,
                'id_rol_prof' => 142,
                'lunes' => 1,
                'martes' => 0,
                'miercoles' => 1,
                'jueves' => 0,
                'viernes' => 1,
                'sabado' => 1,
            ),
            142 => 
            array (
                'id' => 143,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:48',
                'updated_at' => NULL,
                'id_rol_prof' => 143,
                'lunes' => 1,
                'martes' => 0,
                'miercoles' => 1,
                'jueves' => 1,
                'viernes' => 1,
                'sabado' => 1,
            ),
            143 => 
            array (
                'id' => 144,
                'baja' => 0,
                'created_at' => '2023-01-28 03:34:48',
                'updated_at' => NULL,
                'id_rol_prof' => 144,
                'lunes' => 0,
                'martes' => 0,
                'miercoles' => 0,
                'jueves' => 0,
                'viernes' => 0,
                'sabado' => 1,
            ),
        ));
        
        
    }
}